export const ADD = 'Add'
export const EDIT = 'Edit'
export const CANCEL = 'Cancel'
export const SUBMIT = 'Submit'
export const DELETE = 'Delete'
export const IMPORT = 'Import'
export const EXPORT = 'Export'
export const VIEW = 'View'
export const ADD_FILE = 'Click here to upload'
export const VIEW_QUIZ_PLAYERS = 'View players'
export const SELECT_QUIZ_OPTION = 'Select an answer'
export const VIEW_HISTORIQUE = 'View History'
export const GO_TO_HOMEPAGE = 'Go to Homepage'
export const PREVIOUS_QUESTION = 'Previous Question'
export const NEXT_QUESTION = 'Next Question'
export const VIEW_QUIZ_RESULT = 'View Result'

export const LOGOUT = 'Logout'
export const USERS = 'Users'
export const QUIZZES = 'Quizzes'
export const HISTORY = 'History'

export const USER = 'User'

export const LOGIN_MESSAGE = 'Log in'
export const LOGOUT_MODAL_HEADER = 'Logout'
export const LOGOUT_MODAL_MESSAGE = 'Are you sure you want to log out?'
export const LOGOUT_MODAL_BUTTON_LABEL = 'Logout'

export const QUIZ = 'Quiz'
export const QUIZ_TITLE = 'Title'
export const QUIZ_DESCRIPTION = 'Description'
export const QUIZ_TAGS = 'Tags'
export const QUIZ_THUMBNAIL_URL = 'Thumbnail'
export const QUIZ_QUESTIONS = 'Questions'
export const QUIZ_QUESTION = 'Question'
export const QUIZ_OPTIONS = 'Options'
export const QUIZ_PLAYER = 'Player'
export const QUIZ_PLAYERS = 'Players'
export const QUIZ_PLAYED_AT = 'Date'
export const QUIZ_PERCENTAGE = 'Percentage'
export const QUIZ_CORRECT_QUESTIONS = 'Correct Questions'
export const QUIZ_MISSED_QUESTIONS = 'Missed Questions'

export const USER_NAME = 'Name'
export const USER_PROVIDER = 'Provider'
export const USER_EMAIL = 'Email'
export const USER_HISTORY = 'History'
export const USER_SCORE = 'Your Score'

export const MANDATORY = 'Mandatory'
export const AN_OPTION_MUST_BE_SELECTED = 'An option must be selected'
export const INVALID_FILE_FORMAT = 'Invalid file format'
export const DELETE_CONFIRMATION_MESSAGE = 'Do you confirm the deletion?'
export const DELETE_WITH_SUCCESS = 'Successfully deleted'
export const IMPORT_WITH_SUCCESS = 'Successfully imported'
export const LOGOUT_WITH_SUCCESS = 'Successfully logged out'
export const SELECT_ANSWER_IS_MANDATORY = 'You must select an answer'
export const AUTHORIZED_FILE_FORMAT = 'Authorized file format: '

export const BANNER_MESSAGE = 'Test your knowledge with our selected quizzes!'
export const BANNER_SUBMESSAGE =
  'With new quizzes added regularly, there is always something new to discover. Try a new quiz every day and see how much you can learn!'
export const BANNER_BUTTON = 'Explore our quizzes'

export const HOME_PAGE_TITLE = 'Our Quizzes'
export const LOGIN_PAGE_TITLE = 'Log in'
export const LOGIN_WITH_GOOGLE = 'Log in with Google'
export const LOGIN_WITH_GITHUB = 'Log in with Github'
export const CREATE_QUIZ_PAGE_TITLE = 'Create a quiz'
export const UPDATE_QUIZ_PAGE_TITLE = 'Edit quiz'
export const MANAGE_QUIZZES_PAGE_TITLE = 'Quizzes'
export const MANAGE_USERS_PAGE_TITLE = 'Users'
export const NOT_FOUND_PAGE_TITLE = 'Page Not Found'

export const ADMIN_RESERVED_PAGE = 'Only admin users can access this page'
export const LOGGED_IN_RESERVED_PAGE = 'You must log in to access this page'
export const ALL_RIGHTS_RESERVED = '© 2025 Quizz App. All rights reserved'
export const NO_DATA_FOUND = 'No data found'

export const URL_BEFORE_LOGIN = 'url-before-login'
